[main]
font=Iosevka NF:size=11
dpi-aware=no
horizontal-pad=13
vertical-pad=13
inner-pad=13
line-height=21
lines=13
width=55

[border]
radius=5

[colors]
text=cdd6f47f # Text
match=cdd6f4ff
background=1e1e2ecc # Base
selection=1e1e2ecc 
selection-text=cdd6f4ff
selection-match=cdd6f4ff
border=cdd6f41a

# regular0=45475a   # Surface 1
# regular1=f38ba8   # red
# regular2=a6e3a1   # green
# regular3=f9e2af   # yellow
# regular4=89b4fa   # blue
# regular5=f5c2e7   # pink
# regular6=94e2d5   # teal
# regular7=bac2de   # Subtext 1
# bright0=585b70    # Surface 2
# bright1=f38ba8    # red
# bright2=a6e3a1    # green
# bright3=f9e2af    # yellow
# bright4=89b4fa    # blue
# bright5=f5c2e7    # pink
# bright6=94e2d5    # teal
# bright7=a6adc8    # Subtext 0
